services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - sync_database_url=postgresql+psycopg2://postgres:password@postgres:5432/rag_project
      - async_database_url=postgresql+asyncpg://postgres:password@postgres:5432/rag_project
      - redis_url=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: chatbot-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: chatbot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag_project"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot_frontend
    ports:
      - "3000:5173"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data: