"""constarints changed

Revision ID: 658b6e587642
Revises: fd5307e6e245
Create Date: 2026-10-03 11:14:08.296942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658b6e587642'
down_revision: Union[str, Sequence[str], None] = 'fd5307e6e245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_username', 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
